const fs = require("fs")
const inquirer = require("inquirer");
const Engineer = require("./lib/Engineer");
const Manager = require("./lib/Manager")
const Intern = require("./lib/Intern")

let theManager;


/**
 * runs when file is started. 
 * Greets user, creates Manager, adds memebers to Manager team
 * Calls @function buildSite to generate HTML and files 
 * 
 * @async
 * @function init
 */
async function init(){

    console.log("Welcome to the employee database.\nPlease follow the prompts to proceed.\n");

    theManager = new Manager (await addPerson(managerQuestion));

    await addEmployees();

    buildSite();

}

/**
 * Prompt user for details about a person
 * 
 * @async
 * @function addPerson
 * @param {Object} specialQuestion - special question based on which class is calling it
 * @example
 * //returns {Name: "name", ID: "id", email: "email@email.com", officeNum: "num"}
 * addPerson(managerQuestion)
 * @returns {Object} answers - {name, ID, email, specialQuestion}
 */
async function addPerson(specialQuestion){
      
    let answers;
    try{
        answers = await inquirer.prompt(genericQuestions.concat(specialQuestion))
    }
    catch(error){
        console.log(error);
    }
    finally{
        return answers;
    }
}


/**
 * Add an employee to @var theManager 
 *  
 * @async 
 * @function addEmployees
 * @returns {null} - returns -1 when complete
 */
async function addEmployees(){

    let answers;
    try{
        answers = await inquirer.prompt(employeeQuestions)
    }
    catch(error){
        console.log(error);
    }
    finally{
        switch (answers.addPerson){

            case "Engineer":
                theManager.addTeamMember(new Engineer(await addPerson(engineerQuestion)))
                await addEmployees();
                break;
            case "Intern":
                theManager.addTeamMember(new Intern(await addPerson(internQuestion)))
                await addEmployees();
                break;
            default:
                return -1;

        }

    }

}


/**
 * Build HTML from theManger and any/all instances of Engineer or Intern on the team
 */
function buildSite() {
    let thisManager = theManager.getCard();
    let team = theManager.getTeam()
    let teamCards = team.map((emp) => {
            return emp.getCard()
    });
  
    fs.writeFile("./dist/index.html", theWebsite(thisManager,teamCards.toString()), (err) => {
        if (err) throw err;
        console.log("The file has been saved");
    })

    fs.writeFile("./dist/style.css", theCSS() , (err) => {
        if (err) throw err;
        console.log("The file has been saved");
    })

    
}

/**
 * stores questions that will be asked for all persons regardless of Class
 */
const genericQuestions = [
    {
        type: 'input',
        name: 'name',
        message: "Enter employee name",
        validate(value) {
            const valid = isNaN(value);
            return valid || "Answer can not be blank."
        }
    },
    {
        type: 'input',
        name: 'id',
        message: "Enter id number",
        validate(value) {
            return Number.isInteger(parseInt(value)) || "Answer must be a number."
        }
    },
    {
        type: 'input',
        name: 'email',
        message: "Enter email address",
        validate(value) {
            return /\S+@\S+\.\S+/.test(value) || "Enter a valid email"
        }
    },

]

// stores quesitons to be asked only when a Manager class is created
const managerQuestion = [
    {
        type: 'input',
        name: 'officeNum',
        message: "Enter office number"
    },

]

// stores quesitons to be asked only when a Engineer class is created
const engineerQuestion = [
    {
        type: 'input',
        name: 'github',
        message: "Enter github username"
    },

]

// stores quesitons to be asked only when a Intern class is created
const internQuestion = [
    {
        type: 'input',
        name: 'school',
        message: "Enter school name"
    },

]

// stores quesiton to determine what class to create
const employeeQuestions = [
    {
        type: 'list',
        name: 'addPerson',
        message: "Choose an employee to add:",
        choices: ["Engineer" , "Intern", "done"],
        
    },
]


/**
 * creates HTML to be written to file including details from Manager and employees
 * 
 * @param {*} thisManager - HTML generated by Manager class
 * @param  {...any} teamCards - HTML from any employees stores in Manager
 * @returns plain text HTML in the form of a string literal
 */
function theWebsite(thisManager, ...teamCards) {
    return`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Andada+Pro&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="style.css">
    
    
    <title>Employee Directory</title>
</head>
<body>

    <header class="hero">
        <div class="hero-body">
        ${thisManager}
        </div>
    </header>

    <section>
        <div class="columns is-two-thirds is-flex is-justify-content-center is-flex-wrap-wrap">
           ${teamCards}
        </div>
    </section>  

    
</body>
</html>


`;
}


/**
 * creates CSS to be written to file
 * 
 * @returns plain text CSS
 */
function theCSS() { 
    return`
.hero-body{
    background-color: #479E54;
}

.card-header{
    background-color: #9E374F;
}

.card-content{
    background-color: #A6FFB3;
}

li{
    margin: 1%;
    padding: 5px;
    background-color: white;
    border-radius: 5px;
}

section{
    margin: 2rem;
}`

 }


init();